version: '1'
services:
  nginx-react:
    image: reactapp-latest
    container_name: react_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
