export {default as Navbar} from './Navigation/Navbar'
export {default as HomePage} from './HomePage/HomePage'
export {default as AboutMe} from './AboutMe/AboutMe'
export {default as Skills} from './Skills/Skills'
export {default as Projects} from './Projects/Projects'
export {default as SingleProject} from './SingleProject/SingleProject'
export {default as Footer} from './Footer/Footer'